[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[context.production]
  publish = "dist"
  command = "npm run build"

# Site configuration
[site]
  id = "8e272de7-fb1a-4643-bcf0-6df07f143a9e"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[form]
  settings = true
  
[[forms]]
  name = "waitlist-signup"