name: CI & Playwright multi-browser tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Cache Playwright browser binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      - name: Install dependencies
        run: npm ci      - name: Run E2E tests
        run: npm run test:ci

      - name: Assert Lighthouse budgets
        run: npm run assert:lhci

      - name: Run Lighthouse CI
        run: |
          npm run lhci -- \
            --settings.settings.throttlingMethod=provided \
            --maxWaitForLoad=120000
