name: Code Scanning - CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 4 * * *' # daily at 04:00 UTC

jobs:
  analyze:
    name: Perform CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: typescript, javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
        with:
          output: codeql-results.sarif

      - name: Upload SARIF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif
          path: codeql-results.sarif
