name: Secret Scan (gitleaks)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  gitleaks-scan:
    name: Run gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks action
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source=. --report-format=json --report-path=repo-secrets-scan.json --redact

      - name: Upload secrets scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-secrets-scan
          path: |
            repo-secrets-scan.json
            repo-secrets-scan.redacted.txt

      - name: Fail if secrets detected
        if: steps.gitleaks-scan.outputs.exit-code == '1'
        run: |
          echo "Secrets detected by gitleaks. See repo-secrets-scan.json artifact for details."
          exit 1
