name: Secret Scan (gitleaks)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  gitleaks-scan:
    name: Run gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks action
        run: |
          # Install gitleaks
          wget -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks

          # Run gitleaks scan
          ./gitleaks detect --source . --config .gitleaks.toml --report-format json --report-path gitleaks-report.json --redact --verbose || {
            echo "Gitleaks scan completed with findings or errors"
            exit_code=$?
            if [ $exit_code -eq 1 ]; then
              echo "::error::Secrets detected by gitleaks scan"
              cat gitleaks-report.json || echo "Could not read gitleaks report"
              exit 1
            else
              echo "Gitleaks scan failed with exit code $exit_code"
              exit $exit_code
            fi
          }
          echo "No secrets detected"

      - name: Upload secrets scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-secrets-scan
          path: |
            gitleaks-report.json
          if-no-files-found: ignore

      - name: Fail if secrets detected
        if: failure()
        run: |
          echo "Secrets detected by gitleaks or scan failed. Check workflow logs for details."
          exit 1
