name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  npm-audit:
    name: Run npm audit and parse results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Run npm audit and save JSON
        run: npm audit --json > audit.json || true

      - name: Run audit parser and save summary
        run: |
          set -euo pipefail
          node .github/scripts/parse-audit.js audit.json 2>&1 | tee audit-summary.md
          exit ${PIPESTATUS[0]}

      - name: Upload audit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit
          path: |
            audit.json
            audit-summary.md
